project:
  type: book

execute:
  freeze: auto

book:
  title: "Threatened ecosystems of Ruritania"
  subtitle: An IUCN Red List of Ecosystems Assessment
  date: "1234-12-31"
  sidebar:
    collapse-level: 1
  downloads: [pdf]
  chapters:
    - index.qmd
    - content/0.1_foreword.qmd
    - content/0.2_preface.qmd
    - content/0.3_acknowledgments.qmd
    - content/0.4_coordinating_orgs.qmd
    - content/0.5_summary.qmd
    - content/1.0_introduction.qmd
    - content/2_ecosystem_overview.qmd
    - content/3_ecosystem_description.qmd
    - part: "F1.1.3 - INDEF"
      chapters:
        - content/3_ecosystem_assessments/F1.1.3/F1.1.3.qmd
        - content/3_ecosystem_assessments/F1.1.3/F1.1.3_crit_b.qmd
    - part: "F1.2.1 - INDEF"
      chapters:
        - content/3_ecosystem_assessments/F1.2.1/F1.2.1.qmd
        - content/3_ecosystem_assessments/F1.2.1/F1.2.1_crit_b.qmd
    - part: "F1.2.2 - INDEF"
      chapters:
        - content/3_ecosystem_assessments/F1.2.2/F1.2.2.qmd
        - content/3_ecosystem_assessments/F1.2.2/F1.2.2_crit_b.qmd
    - part: "F2.1.1 - INDEF"
      chapters:
        - content/3_ecosystem_assessments/F2.1.1/F2.1.1.qmd
        - content/3_ecosystem_assessments/F2.1.1/F2.1.1_crit_b.qmd
    - part: "F2.2.1 - INDEF"
      chapters:
        - content/3_ecosystem_assessments/F2.2.1/F2.2.1.qmd
        - content/3_ecosystem_assessments/F2.2.1/F2.2.1_crit_b.qmd
    - part: "F2.3.1 - INDEF"
      chapters:
        - content/3_ecosystem_assessments/F2.3.1/F2.3.1.qmd
        - content/3_ecosystem_assessments/F2.3.1/F2.3.1_crit_b.qmd
    - part: "F3.1.1 - INDEF"
      chapters:
        - content/3_ecosystem_assessments/F3.1.1/F3.1.1.qmd
        - content/3_ecosystem_assessments/F3.1.1/F3.1.1_crit_b.qmd
    - part: "FM1.2.1 - INDEF"
      chapters:
        - content/3_ecosystem_assessments/FM1.2.1/FM1.2.1.qmd
        - content/3_ecosystem_assessments/FM1.2.1/FM1.2.1_crit_b.qmd
    - part: "MFT1.2.1 - Amazon-Orinoco-Southern Caribbean mangroves"
      chapters:
        - content/3_ecosystem_assessments/MFT1.2.1/MFT1.2.1.qmd
        - content/3_ecosystem_assessments/MFT1.2.1/MFT1.2.1_crit_b.qmd
    - part: "T1.1.1 - Apure-Villavicencio dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.1.1/T1.1.1.qmd
        - content/3_ecosystem_assessments/T1.1.1/T1.1.1_crit_b.qmd
    - part: "T1.1.16 - Magdalena-Urabá moist forests"
      chapters:
        - content/3_ecosystem_assessments/T1.1.16/T1.1.16.qmd
        - content/3_ecosystem_assessments/T1.1.16/T1.1.16_crit_b.qmd
    - part: "T1.1.19 - Magdalena-Urabá moist forests"
      chapters:
        - content/3_ecosystem_assessments/T1.1.19/T1.1.19.qmd
        - content/3_ecosystem_assessments/T1.1.19/T1.1.19_crit_b.qmd
    - part: "T1.1.6 - Catatumbo moist forests"
      chapters:
        - content/3_ecosystem_assessments/T1.1.6/T1.1.6.qmd
        - content/3_ecosystem_assessments/T1.1.6/T1.1.6_crit_b.qmd
    - part: "T1.2.1 - Catatumbo Ocaña dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.1/T1.2.1.qmd
        - content/3_ecosystem_assessments/T1.2.1/T1.2.1_crit_b.qmd
    - part: "T1.2.11 - Guajira-Barranquilla xeric scrub"
      chapters:
        - content/3_ecosystem_assessments/T1.2.11/T1.2.11.qmd
        - content/3_ecosystem_assessments/T1.2.11/T1.2.11_crit_b.qmd
    - part: "T1.2.12 - Guajira-Barranquilla xeric scrub"
      chapters:
        - content/3_ecosystem_assessments/T1.2.12/T1.2.12.qmd
        - content/3_ecosystem_assessments/T1.2.12/T1.2.12_crit_b.qmd
    - part: "T1.2.13 - Guajira-Barranquilla xeric scrub"
      chapters:
        - content/3_ecosystem_assessments/T1.2.13/T1.2.13.qmd
        - content/3_ecosystem_assessments/T1.2.13/T1.2.13_crit_b.qmd
    - part: "T1.2.15 - Magdalena Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.15/T1.2.15.qmd
        - content/3_ecosystem_assessments/T1.2.15/T1.2.15_crit_b.qmd
    - part: "T1.2.16 - Magdalena Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.16/T1.2.16.qmd
        - content/3_ecosystem_assessments/T1.2.16/T1.2.16_crit_b.qmd
    - part: "T1.2.17 - Magdalena Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.17/T1.2.17.qmd
        - content/3_ecosystem_assessments/T1.2.17/T1.2.17_crit_b.qmd
    - part: "T1.2.19 - Patìa-Dagua dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.19/T1.2.19.qmd
        - content/3_ecosystem_assessments/T1.2.19/T1.2.19_crit_b.qmd
    - part: "T1.2.2 - Catatumbo Ocaña dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.2/T1.2.2.qmd
        - content/3_ecosystem_assessments/T1.2.2/T1.2.2_crit_b.qmd
    - part: "T1.2.20 - Patìa-Dagua dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.20/T1.2.20.qmd
        - content/3_ecosystem_assessments/T1.2.20/T1.2.20_crit_b.qmd
    - part: "T1.2.21 - Patìa-Dagua dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.21/T1.2.21.qmd
        - content/3_ecosystem_assessments/T1.2.21/T1.2.21_crit_b.qmd
    - part: "T1.2.22 - Patìa-Dagua dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.22/T1.2.22.qmd
        - content/3_ecosystem_assessments/T1.2.22/T1.2.22_crit_b.qmd
    - part: "T1.2.23 - Patìa-Dagua dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.23/T1.2.23.qmd
        - content/3_ecosystem_assessments/T1.2.23/T1.2.23_crit_b.qmd
    - part: "T1.2.24 - Sinú Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.24/T1.2.24.qmd
        - content/3_ecosystem_assessments/T1.2.24/T1.2.24_crit_b.qmd
    - part: "T1.2.25 - Sinú Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.25/T1.2.25.qmd
        - content/3_ecosystem_assessments/T1.2.25/T1.2.25_crit_b.qmd
    - part: "T1.2.26 - Sinú Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.26/T1.2.26.qmd
        - content/3_ecosystem_assessments/T1.2.26/T1.2.26_crit_b.qmd
    - part: "T1.2.27 - Sinú Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.27/T1.2.27.qmd
        - content/3_ecosystem_assessments/T1.2.27/T1.2.27_crit_b.qmd
    - part: "T1.2.28 - Magdalena Valley montane forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.28/T1.2.28.qmd
        - content/3_ecosystem_assessments/T1.2.28/T1.2.28_crit_b.qmd
    - part: "T1.2.4 - Cauca Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.4/T1.2.4.qmd
        - content/3_ecosystem_assessments/T1.2.4/T1.2.4_crit_b.qmd
    - part: "T1.2.5 - Cauca Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.5/T1.2.5.qmd
        - content/3_ecosystem_assessments/T1.2.5/T1.2.5_crit_b.qmd
    - part: "T1.2.6 - Cauca Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.6/T1.2.6.qmd
        - content/3_ecosystem_assessments/T1.2.6/T1.2.6_crit_b.qmd
    - part: "T1.2.8 - Chicamocha Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/T1.2.8/T1.2.8.qmd
        - content/3_ecosystem_assessments/T1.2.8/T1.2.8_crit_b.qmd
    - part: "T1.3.31 - Magdalena Valley montane forests"
      chapters:
        - content/3_ecosystem_assessments/T1.3.31/T1.3.31.qmd
        - content/3_ecosystem_assessments/T1.3.31/T1.3.31_crit_b.qmd
    - part: "T1.3.33 - Magdalena Valley montane forests"
      chapters:
        - content/3_ecosystem_assessments/T1.3.33/T1.3.33.qmd
        - content/3_ecosystem_assessments/T1.3.33/T1.3.33_crit_b.qmd
    - part: "T1.3.34 - Northwest Andean montane forests"
      chapters:
        - content/3_ecosystem_assessments/T1.3.34/T1.3.34.qmd
        - content/3_ecosystem_assessments/T1.3.34/T1.3.34_crit_b.qmd
    - part: "T1.3.36 - Northwest Andean montane forests"
      chapters:
        - content/3_ecosystem_assessments/T1.3.36/T1.3.36.qmd
        - content/3_ecosystem_assessments/T1.3.36/T1.3.36_crit_b.qmd
    - part: "T1.3.5 - Cauca Valley montane forests"
      chapters:
        - content/3_ecosystem_assessments/T1.3.5/T1.3.5.qmd
        - content/3_ecosystem_assessments/T1.3.5/T1.3.5_crit_b.qmd
    - part: "T3.1.1 - Pantepui"
      chapters:
        - content/3_ecosystem_assessments/T3.1.1/T3.1.1.qmd
        - content/3_ecosystem_assessments/T3.1.1/T3.1.1_crit_b.qmd
    - part: "T4.2.12 - Sinú Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/T4.2.12/T4.2.12.qmd
        - content/3_ecosystem_assessments/T4.2.12/T4.2.12_crit_b.qmd
    - part: "T4.2.2 - Llanos"
      chapters:
        - content/3_ecosystem_assessments/T4.2.2/T4.2.2.qmd
        - content/3_ecosystem_assessments/T4.2.2/T4.2.2_crit_b.qmd
    - part: "T4.2.5 - Llanos"
      chapters:
        - content/3_ecosystem_assessments/T4.2.5/T4.2.5.qmd
        - content/3_ecosystem_assessments/T4.2.5/T4.2.5_crit_b.qmd
    - part: "T5.2.1 - Guajira-Barranquilla xeric scrub"
      chapters:
        - content/3_ecosystem_assessments/T5.2.1/T5.2.1.qmd
        - content/3_ecosystem_assessments/T5.2.1/T5.2.1_crit_b.qmd
    - part: "T5.2.2 - Guajira-Barranquilla xeric scrub"
      chapters:
        - content/3_ecosystem_assessments/T5.2.2/T5.2.2.qmd
        - content/3_ecosystem_assessments/T5.2.2/T5.2.2_crit_b.qmd
    - part: "T5.2.3 - Magdalena Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/T5.2.3/T5.2.3.qmd
        - content/3_ecosystem_assessments/T5.2.3/T5.2.3_crit_b.qmd
    - part: "TF1.1.5 - Andean Alluvial forests"
      chapters:
        - content/3_ecosystem_assessments/TF1.1.5/TF1.1.5.qmd
        - content/3_ecosystem_assessments/TF1.1.5/TF1.1.5_crit_b.qmd
    - part: "TF1.5.2 - Magdalena Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/TF1.5.2/TF1.5.2.qmd
        - content/3_ecosystem_assessments/TF1.5.2/TF1.5.2_crit_b.qmd
    - part: "TF1.5.3 - Sinú Valley dry forests"
      chapters:
        - content/3_ecosystem_assessments/TF1.5.3/TF1.5.3.qmd
        - content/3_ecosystem_assessments/TF1.5.3/TF1.5.3_crit_b.qmd
    - references.qmd

bibliography: 
  - references_iucn.bib
  - references_country_specific.bib

number-sections: false

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt

show-instructions: true
tbl-cap-location: top

# Content Constants
country-name: Ruritania
country-code: XX  # https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
version: 0.1
year: 1234
