project:
  type: book

execute:
  freeze: auto

book:
  title: "Threatened ecosystems of Ruritania"
  subtitle: An IUCN Red List of Ecosystems Assessment
  date: "1234-12-31"
  sidebar:
    collapse-level: 1
  downloads: [pdf]
  chapters:
    - index.qmd
    - content/0.1_foreword.qmd
    - content/0.2_preface.qmd
    - content/0.3_acknowledgments.qmd
    - content/0.4_coordinating_orgs.qmd
    - content/0.5_summary.qmd
    - content/1.0_introduction.qmd
    - content/2_ecosystem_overview.qmd
    - content/3_ecosystem_description.qmd
    - part: "M1.1.1 - Null Island Marine Shelf"
      chapters:
        - content/3_ecosystem_assessments/M1.1.1/M1.1.1.qmd
        - content/3_ecosystem_assessments/M1.1.1/M1.1.1_crit_b.qmd
    - part: "T1.1.1 - Null Island Tropical Forest"
      chapters:
        - content/3_ecosystem_assessments/T1.1.1/T1.1.1.qmd
        - content/3_ecosystem_assessments/T1.1.1/T1.1.1_crit_b.qmd
    - part: "T6.5.1 - Null Island Alpine Grassland"
      chapters:
        - content/3_ecosystem_assessments/T6.5.1/T6.5.1.qmd
        - content/3_ecosystem_assessments/T6.5.1/T6.5.1_crit_b.qmd
    - references.qmd

bibliography: 
  - references_iucn.bib
  - references_country_specific.bib

number-sections: false

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt

show-instructions: true
tbl-cap-location: top

# Content Constants
country-name: Ruritania
country-code: XX  # https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2
version: 0.1
year: 1234
