---
jupyter: python3
keep-ipynb: true
format:
  html:
    other-links:
      - text: Download Notebook
        icon: journal-code
        href: 2_ecosystem_overview.ipynb
title: "Terrestrial Ecosystems of {{< meta country-name >}}"
numbering:
  figure:
    enumerator: 2.%s
---

```{python}
#| label: import-modules
#| echo: false
#| output: false
import os
from pprint import pprint

import geopandas as gpd
import yaml

import rle_python_gee
import iucn_get_data
from iucn_get_data import open_ecosystem_map, Typology

print(f'{rle_python_gee.__version__ = }')
print(f'{iucn_get_data.__version__ = }')
```

```{python}
#| label: load-country-config
#| echo: false
#| output: false
# Load up the country-level configuration.
with open('../config/country_config.yaml', 'r') as f:
    config = yaml.safe_load(f)
pprint(config)
```

```{python}
#| label: initialize-google-earth-engine
#| echo: false
# Initialize Google Earth Engine.
# rle_python_gee.ee_auth.initialize_ee(project=os.environ['GOOGLE_CLOUD_PROJECT'])
```


```{python}
#| label: load-ecosystems-data
#| echo: false
#| output: false
# Load the country's ecosystems data as a pandas DataFrame.
ecosystems = open_ecosystem_map(
    config['ecosystem_source']['data'],
    get_level3_column=config['ecosystem_source']['functional_group_column'],
    get_level456_column=config['ecosystem_source']['ecosystem_code_column']
)

ecosystems_df = ecosystems.functional_group_dataframe()
ecosystems_df
```

```{python}
#| label: calculate-ecosystem-type-and-biome-counts
#| echo: false
ecosystem_type_count = len(ecosystems_df)
biome_count = len(ecosystems_df.index.get_level_values('EFG1').unique())
```


The {{< meta country-name >}} ecosystem typology includes `{python} ecosystem_type_count` ecosystem types across `{python} biome_count` biomes (@tbl-typology).
The ecosystem typology is consistent with the IUCN global ecosystem typology [@keith2020get]
to support crosswalks and comparisons with Red Lists of ecosystems in other countries and
regions. The {{< meta country-name >}} ecosystem typology has a hierarchical structure, where each ecosystem type is assigned to a realm, biome and functional group (ecotype).
Realm refers to one of the four component media in the biosphere (@fig-realm-distribution),
biome is the segment of the biosphere united by major functional traits and macro-environmental features (@fig-biome-distribution),
and functional group is a group of related ecosystems within a biome (@fig-functional-group-distribution).
The distribution of {{< meta country-name >}}’s ecosystem types is shown in @fig-heat-map-ecosystems,
and map data is made publicly available ([reference?]{.mark}).

```{python}
#| label: create-typology
#| echo: false
typology_es = iucn_get_data.Typology(
    language="spanish",
    ecosystems=ecosystems_df.drop(columns=['COD_new', 'ECRG', 'EFG2', 'EFG_Etter', 'GETyp_CODn'], errors='ignore'),
    ecosystems_functional_group_column='EFG1',
    ecosystems_column='ECO_CODE',
    ecosystem_name_column='ECO_NAME',
)
```


```{python}
#| label: tbl-typology
#| echo: false
#| tbl-cap: "List of the terrestrial ecosystems of {{< meta country-name >}} developed in this project."
typology_es
```

```{python}
#| label: fig-realm-distribution
#| echo: false
#| fig-cap: "The distribution of the realms of {{< meta country-name >}}."
m_realm = ecosystems.to_realm_map(view_state=config['view_state'])
m_realm
```

```{python}
#| label: fig-biome-distribution
#| echo: false
#| fig-cap: "The distribution of the biomes of {{< meta country-name >}}."
m_biome = ecosystems.to_biome_map(view_state=config['view_state'])
m_biome
```

```{python}
#| label: fig-functional-group-distribution
#| echo: false
#| fig-cap: "The distribution of the biomes of {{< meta country-name >}}."
ecosystems.to_functional_group_map(view_state=config['view_state'])
```

```{python}
#| label: fig-heat-map-ecosystems
#| echo: false
#| fig-cap: "Heat map of the distribution of natural ecosystem types of {{< meta country-name >} mapped as the number of ecosystems intersecting a 10 x 10 km grid."
print('(Heat map of the distribution of natural ecosystem types not implemented yet.)')
```


::: {.content-hidden unless-meta="show-instructions"}

:::: {.callout-important}
## How to customize the Ecosystem Overview page

- To modify the ecosystem overview text, edit the `content/2_ecosystem_overview.qmd` file.
- To remove the ecosystem overview section, edit the `_quarto.yml` file and remove the
  `- content/2_ecosystem_overview.qmd` line.

**To hide these instructions on all pages, set `show-instructions: false`
in the `_quarto.yml` file.**
::::
:::
