country_name: Ruritania
country_code: RU
view_state:
  longitude: 18.51
  latitude: -34.02
  zoom: 10
ecosystem_source:
  data: https://storage.googleapis.com/rle_test_data/colombia_ecosystems.parquet
  ecosystem_code_column: ECO_CODE
  ecosystem_name_column: ECO_NAME
  functional_group_column: EFG1
